# Generated by Django 5.0 on 2024-01-26 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('totalseats', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('5:00 AM', '5:00 AM'), ('10:10 AM', '10:10 AM'), ('2:15 PM', '2:15 PM'), ('5:30 PM', '5:30 PM'), ('8:30 PM', '8:30 PM'), ('11:45 PM', '11:45 PM')], max_length=255)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theater', to='home.movie')),
                ('tname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtime', to='home.theater')),
            ],
        ),
    ]
